[workspace]
resolver = "2"
members = [
    "backend",
    "shared",
    "android/app/src/main/rust",
    "windows", "quic-tester",
]

[workspace.dependencies]
shared = { path = "shared" }
tokio = { version = "1.0", features = ["full"] }
quinn = { version = "0.11", features = ["rustls"] }
rustls = { version = "0.23", default-features = false, features = ["ring", "std"] }
anyhow = "1.0"
bytes = "1.0"
socket2 = { version = "0.6", features = ["all"] }
serde = { version = "1.0", features = ["derive"] }
bincode = { package = "bincode-next", version = "3.0.0-rc.2", features = ["serde"] }
tracing = "0.1"
time = "=0.3.36"
rcgen = "0.14"
rustls-pemfile = "2.0"
ipnetwork = "0.21"
etherparse = "0.19"
dashmap = "6.1"
thiserror = "2.0"

[patch.crates-io]
quinn = { path = "external/quinn/quinn" }
quinn-proto = { path = "external/quinn/quinn-proto" }
quinn-udp = { path = "external/quinn/quinn-udp" }
time = { git = "https://github.com/time-rs/time", tag = "v0.3.36" }

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = true
