[workspace]
resolver = "2"
members = [
    "backend",
    "shared",
]

[workspace.dependencies]
shared = { path = "shared" }
tokio = { version = "1.0", features = ["full"] }
quinn = "0.11"
rustls = { version = "0.23", default-features = false, features = ["ring", "std"] }
anyhow = "1.0"
bytes = "1.0"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
tracing = "0.1"
time = "=0.3.36"
