[workspace]
resolver = "2"
members = [
    "backend",
    "shared",
    "android/app/src/main/rust",
]

[workspace.dependencies]
shared = { path = "shared" }
tokio = { version = "1.0", features = ["full"] }
quinn = { version = "0.11", features = ["rustls"] }
rustls = { version = "0.23", default-features = false, features = ["ring", "std"] }
anyhow = "1.0"
bytes = "1.0"
socket2 = "0.5"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
tracing = "0.1"
time = "=0.3.36"
rcgen = "0.13"
rustls-pemfile = "2.0"
ipnetwork = "0.20"
etherparse = "0.13"
dashmap = "5.5"
thiserror = "1.0"

[patch.crates-io]
time = { git = "https://github.com/time-rs/time", tag = "v0.3.36" }

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = true
